---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "streamlit-app"
  namespace: "default"
  labels:
    app: "latin-vocab"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "latin-vocab"
  template:
    metadata:
      labels:
        app: "latin-vocab"
    spec:
      containers:
      - name: "latin-vocab"
        image: "streamlit-app:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "streamlit-app-hpa-cvvn"
  namespace: "default"
  labels:
    app: "streamlit-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "streamlit-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
